name: common
apiVersion: v2
appVersion: 1.4.0
version: 1.4.0
description: A Library Helm Chart for grouping common logic for universal chart. This chart is not deployable by itself.
annotations:
  category: Infrastructure