{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled (gt (len .Values.metrics.prometheusRule.groups) 0) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ default (include "common.names.namespace" .) .Values.metrics.prometheusRule.namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- if .Values.metrics.prometheusRule.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.metrics.prometheusRule.additionalLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  groups:
  {{- range .Values.metrics.prometheusRule.groups }}
    - name: {{ .name }}
      {{- if .interval }}
      interval: {{ .interval }}
      {{- end }}
      rules:
      {{- range .rules }}
        {{- if .alert }}
        - alert: {{ .alert }}
        {{- else if .record }}
        - record: {{ .record }}
        {{- end }}
          expr: {{ .expr | toYaml | nindent 12 | trim }}
          {{- if .for }}
          for: {{ .for }}
          {{- end }}
          {{- if .labels }}
          labels:
            {{- toYaml .labels | nindent 12 }}
          {{- end }}
          {{- if .annotations }}
          annotations:
            {{- toYaml .annotations | nindent 12 }}
          {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
